## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for detail
language: c
sudo: required

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap

install:
  - ./pkg-build.sh install_deps

script:
  - ./pkg-build.sh run_tests

# print timings (of examples) and sysinfo
after_script:
  - ./pkg-build.sh dump_logs_by_extension "timings"
  - ./pkg-build.sh dump_sysinfo

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    recipients:
    - szoecs@uni-landau.de
    on_success: never
    on_failure: always

env:
  matrix:
    - RVERSION=release
    - RVERSION=devel COVERAGE=true

  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --as-cran --run-donttest"
    - _R_CHECK_TIMINGS_="0"
 
