language: r
sudo: false
cache: packages

r:
  - devel
  - release

env:
  global:
    - _R_CRAN_CHECK_INCOMING_=false


r_check_args: "--no-build-vignettes --no-manual --timings --as-cran"
warnings_are_errors: false
r_check_revdep: false


r_packages:
  - devtools

r_github_packages:
  - jimhester/covr

# report to codecov
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'

# report to maintainer
notifications:
  email:
    recipients:
    - eduardszoecs@gmail.com
    on_success: change
    on_failure: change

